version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.2
  jq: {}
filters: &filters
  tags:
    only: /.*/
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
executors:
  docker-base:
    docker:
      - image: cimg/base:stable
    shell: bash -eox pipefail
  alpine:
    docker:
      - image: alpine:latest
    shell: sh -eox pipefail
  macos:
    macos:
      xcode: 14.2.0
    shell: bash -eox pipefail
  machine:
    machine:
      image: ubuntu-2004:current
    shell: bash -eox pipefail
  arm:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    shell: bash -eox pipefail

jobs:
  install:
    parameters:
      executor:
        type: executor
      version:
        type: string
        default: latest
      override:
        type: boolean
        default: false
    executor: <<parameters.executor>>
    steps:
      - jq/install:
          version: <<parameters.version>>
          override: <<parameters.override>>
      - checkout
      - run:
          name: Verify version
          command: |
            export "PATH=$PATH:~/bin"
            if [ <<parameters.version>> = "latest" ]; then
              JQ_VERSION=$(wget -q --server-response -O /dev/null "https://github.com/jqlang/jq/releases/latest" 2>&1 | awk '/^  Location: /{print $2}' | sed 's:.*/::')
            else
              JQ_VERSION=<<parameters.version>>
            fi
            jq --version | grep $JQ_VERSION

workflows:
  integration_tests-prod_deploy:
    jobs:
      # latest
      - install:
          name: install-latest-alpine
          executor: alpine
          context: orb-publisher

      - install:
          name: install-latest-machine
          executor: machine
          context: orb-publisher

      - install:
          name: install-latest-macos
          executor: macos
          context: orb-publisher

      - install:
          name: install-latest-docker
          executor: docker-base
          context: orb-publisher
      - install:
          name: install-jq-1.7-<<matrix.executor>>
          matrix:
            parameters:
              executor: [alpine, macos, machine, docker-base, arm]
          version: jq-1.7
          override: true
      # older jq
      - install:
          name: install-older-alpine
          executor: alpine
          version: jq-1.5
          context: orb-publisher

      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/jq
          vcs_type: << pipeline.project.type >>
          pub_type: production
          enable_pr_comment: true
          requires: [orb-tools/pack, ]
          context: orb-publisher
          filters: *release-filters